### ISSUE TITLE
 No such file or directory: 'analysis.html'

### ISSUE THREAD

**Issue by waveBridge** [vita-epfl/openpifpafwebdemo#7]
excuse me，I have a problem.
I download your code and to run the server.
The service was started, but when I visited http://localhost:5000,there is a error.
`FileNotFoundError: [Errno 2] No such file or directory: 'analysis.html'`

**Comment by svenkreiss** [comment]
Strange. Please make sure you don't have conflicting versions, i.e. do not clone this repository and also do `pip install openpifpafwebdemo`. 

If that is not it:
Which operating system are you on?
Did you clone or use `pip install openpifpafwebdemo`?

**Comment by HuAndrew** [comment]
**I can test single images successfully.** 

**But run openpifpafwebdemo.server occur the same problems as follow:** 

```bash
Traceback (most recent call last):
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\databench\meta.py", line 269, in get
    **self.info)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\web.py", line 766, in render
    html = self.render_string(template_name, **kwargs)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\web.py", line 904, in render_string
    t = loader.load(template_name)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\template.py", line 425, in load
    self.templates[name] = self._create_template(name)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\databench\template.py", line 29, in _create_template
    f.read(), name=name, loader=self)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\template.py", line 305, in __init__
    self.code = self._generate_python(loader)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\template.py", line 353, in _generate_python
    ancestors = self._get_ancestors(loader)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\template.py", line 371, in _get_ancestors
    template = loader.load(chunk.name, self.name)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\tornado\template.py", line 425, in load
    self.templates[name] = self._create_template(name)
  File "E:\Program Files\PyTools\Anaconda3\lib\site-packages\databench\template.py", line 27, in _create_template
    with open(name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'analysis.html'
```

**Comment by HuAndrew** [comment]
Ans I test in windows10 platform.

**Comment by svenkreiss** [comment]
I am trying to setup unit tests for Windows to reproduce the problem, but it is not easy for me. For reference: https://github.com/svenkreiss/databench/pull/67

Has anyone seen this on a different platform than windows?

**Comment by HuAndrew** [comment]
Thanks for sharing your work.

**Comment by svenkreiss** [comment]
Is this fixed with the new databench? 
I.e. run `pip install --upgrade databench` before trying again?

**Comment by HuAndrew** [comment]
It's very perfect! Thanks a lot.

**Comment by svenkreiss** [comment]
Great! Thanks for confirming.
